service: API-Example-Express

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
